### PR TITLE
make bow docker images smaller

### PR DESCRIPTION
**Pull request by JermineHu**
Used alpine image will make this docker image  smaller

### CODE REVIEW

**Comment by Evedel** [comment]
Hi @JermineHu, thank you for a pr! This is a good idea to have a light version. I definitely want to keep both images altogether, though. As because of layers system the overcome of debian vs alpine is based mostly on which base image is used for the rest of infrastructure.
If you don't mind, I'll have a look on it at this weekends, to see what is the best way to keep them both, probably this will be some sort of subtags with base image name on dockerhub.

**Comment by JermineHu** [comment]
Many versions of the docker image fully agree! I prefer smaller an image！I have already submitted second pr，This time PR you are free

**Comment by Evedel** [comment]
Sure, the smaller the better, but I prefer to keep backward compatibility, as well, if there is no urgent reason to do opposite things. This is why I will stick with debian image at ```bow:latest```, and will add subname ```bow/alpine:latest``` for other base images, so people can choose whatever they like more.

The second, because of the layer system, it doesn't matter what the base image is, while it is the same base image across all the infrastructure. You'll only need to get diff layer (app layer in this case) which has the same size in both cases.

**Comment by JermineHu** [comment]
Yes ，I know the docker images used layer system. I agree that multiple versions are suitable for different scenarios .

**Pull request closed without merging**
